### PR TITLE
Fix encoding issue

### PR DESCRIPTION
**Pull request by tclementdev**
- Fix encoding issue by not using CGImageCreateWithImageInRect+CGImageGetDataProvider+CGDataProviderCopyData (Quartz bug).
- Fix an issue where the CGImageAlphaInfo was treated as a bitfield instead of a plain enum.

### CODE REVIEW

**Comment by alexzielenski** [comment]
I just tried your version of the tool and the encoding issue is still not fixed :(

**Comment by tclementdev** [comment]
Ok then I don't understand what the issue is. I have decoded the ArtFile.bin, encoded the result, then decoded what I just encoded. Well the final decoding output looks just like the first one, all the images look fine.

How can I reproduce the issue and how can I see that there is an issue?

**Comment by alexzielenski** [comment]
Decode with the "-c" option and then re-encode with the "-c" option. When you log in and out some image would have degraded quality. Specifically toolbar segment images like the ones in Finder. I think perhaps it might be just the usage of CGImage that is doing this.

**Comment by tclementdev** [comment]
I see. And if you decode the new artfile and look directly at the png, can you see the same degraded quality?

**Comment by alexzielenski** [comment]
Nope

**Comment by tclementdev** [comment]
Ok this is weird. I don't see why CGImage would be the problem since it seems to give correct pixel values. Please note that I did see pixel issues on some of the images (which is probably due to the Quartz bug I mentioned when using CGImageCreateWithImageInRect) and that these issues went away with this code change (which is why I though the encoding issue was fixed).

I'll do some more testing and keep you up-to-date if I find anything interesting.

Thanks!

**Comment by tclementdev** [comment]
So I finally tried it for real, I decoded then encoded using the "-c" option. I replaced the ArtFile.bin file in my system with the encoded one, I did logout/login, I even rebooted. And I cannot see any "degraded quality" image, the Finder toolbar looks fine as always, I navigated in various applications, tested various interface controls, everything looks good. I tried this on two machines running 10.6 and 10.7, same thing.

Am I doing something wrong? If not, are you sure you tested the tool from my code fork?

**Comment by alexzielenski** [comment]
Screenshot? Im sure i used your fork.

**Comment by tclementdev** [comment]
Screenshot of what? The interface looks just like any standard os x installation.

**Pull request closed without merging**
